version: '3.1'

services:
  db:
    image: postgres:14.1
    restart: "no"
    environment:
      POSTGRES_PASSWORD: notsecurepass
    ports:
      - 15432:5432
    # volumes:
    #   - /home/rodrigo/_docker_volumes/postgres:/var/lib/postgresql/data 
